/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAlGrupoPorNombreResponseBuilder {
    //the instance to build
    private CrearUnMensajeAlGrupoPorNombreResponse crearUnMensajeAlGrupoPorNombreResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAlGrupoPorNombreResponseBuilder() {
        crearUnMensajeAlGrupoPorNombreResponse = new CrearUnMensajeAlGrupoPorNombreResponse();
    }

    public CrearUnMensajeAlGrupoPorNombreResponseBuilder data(Data5 data) {
        crearUnMensajeAlGrupoPorNombreResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAlGrupoPorNombreResponse build() {
        return crearUnMensajeAlGrupoPorNombreResponse;
    }
}