/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeResponseBuilder {
    //the instance to build
    private CrearUnMensajeResponse crearUnMensajeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeResponseBuilder() {
        crearUnMensajeResponse = new CrearUnMensajeResponse();
    }

    public CrearUnMensajeResponseBuilder data(Data5 data) {
        crearUnMensajeResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeResponse build() {
        return crearUnMensajeResponse;
    }
}