/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAAplicaciNRequestBuilder {
    //the instance to build
    private CrearUnMensajeAAplicaciNRequest crearUnMensajeAAplicaciNRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAAplicaciNRequestBuilder() {
        crearUnMensajeAAplicaciNRequest = new CrearUnMensajeAAplicaciNRequest();
    }

    public CrearUnMensajeAAplicaciNRequestBuilder leido(boolean leido) {
        crearUnMensajeAAplicaciNRequest.setLeido(leido);
        return this;
    }

    public CrearUnMensajeAAplicaciNRequestBuilder borrado(boolean borrado) {
        crearUnMensajeAAplicaciNRequest.setBorrado(borrado);
        return this;
    }

    public CrearUnMensajeAAplicaciNRequestBuilder data(Data data) {
        crearUnMensajeAAplicaciNRequest.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAAplicaciNRequest build() {
        return crearUnMensajeAAplicaciNRequest;
    }
}