/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CrearUnMensajeRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5377809502417205211L;
    private boolean leido;
    private boolean borrado;
    private Data14 data;
    private String expireAt;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leido")
    public boolean getLeido ( ) { 
        return this.leido;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leido")
    public void setLeido (boolean value) { 
        this.leido = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("borrado")
    public boolean getBorrado ( ) { 
        return this.borrado;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("borrado")
    public void setBorrado (boolean value) { 
        this.borrado = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public Data14 getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (Data14 value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expireAt")
    public String getExpireAt ( ) { 
        return this.expireAt;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expireAt")
    public void setExpireAt (String value) { 
        this.expireAt = value;
    }
 
}
 