/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAlGrupoPorNombreRequestBuilder {
    //the instance to build
    private CrearUnMensajeAlGrupoPorNombreRequest crearUnMensajeAlGrupoPorNombreRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAlGrupoPorNombreRequestBuilder() {
        crearUnMensajeAlGrupoPorNombreRequest = new CrearUnMensajeAlGrupoPorNombreRequest();
    }

    public CrearUnMensajeAlGrupoPorNombreRequestBuilder leido(boolean leido) {
        crearUnMensajeAlGrupoPorNombreRequest.setLeido(leido);
        return this;
    }

    public CrearUnMensajeAlGrupoPorNombreRequestBuilder borrado(boolean borrado) {
        crearUnMensajeAlGrupoPorNombreRequest.setBorrado(borrado);
        return this;
    }

    public CrearUnMensajeAlGrupoPorNombreRequestBuilder data(Data data) {
        crearUnMensajeAlGrupoPorNombreRequest.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAlGrupoPorNombreRequest build() {
        return crearUnMensajeAlGrupoPorNombreRequest;
    }
}