/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAlGrupoResponseBuilder {
    //the instance to build
    private CrearUnMensajeAlGrupoResponse crearUnMensajeAlGrupoResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAlGrupoResponseBuilder() {
        crearUnMensajeAlGrupoResponse = new CrearUnMensajeAlGrupoResponse();
    }

    public CrearUnMensajeAlGrupoResponseBuilder data(Data5 data) {
        crearUnMensajeAlGrupoResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAlGrupoResponse build() {
        return crearUnMensajeAlGrupoResponse;
    }
}