/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CrearUnMensajeAlGrupoPorNombreResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5451455911647722629L;
    private Data5 data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public Data5 getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (Data5 value) { 
        this.data = value;
    }
 
}
 