/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeRequestBuilder {
    //the instance to build
    private CrearUnMensajeRequest crearUnMensajeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeRequestBuilder() {
        crearUnMensajeRequest = new CrearUnMensajeRequest();
    }

    public CrearUnMensajeRequestBuilder leido(boolean leido) {
        crearUnMensajeRequest.setLeido(leido);
        return this;
    }

    public CrearUnMensajeRequestBuilder borrado(boolean borrado) {
        crearUnMensajeRequest.setBorrado(borrado);
        return this;
    }

    public CrearUnMensajeRequestBuilder data(Data14 data) {
        crearUnMensajeRequest.setData(data);
        return this;
    }

    public CrearUnMensajeRequestBuilder expireAt(String expireAt) {
        crearUnMensajeRequest.setExpireAt(expireAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeRequest build() {
        return crearUnMensajeRequest;
    }
}