/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnGrupoRequestBuilder {
    //the instance to build
    private CrearUnGrupoRequest crearUnGrupoRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnGrupoRequestBuilder() {
        crearUnGrupoRequest = new CrearUnGrupoRequest();
    }

    public CrearUnGrupoRequestBuilder nombre(String nombre) {
        crearUnGrupoRequest.setNombre(nombre);
        return this;
    }

    public CrearUnGrupoRequestBuilder aplicacion(String aplicacion) {
        crearUnGrupoRequest.setAplicacion(aplicacion);
        return this;
    }

    public CrearUnGrupoRequestBuilder usuarios(List<String> usuarios) {
        crearUnGrupoRequest.setUsuarios(usuarios);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnGrupoRequest build() {
        return crearUnGrupoRequest;
    }
}