/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAAplicaciNResponseBuilder {
    //the instance to build
    private CrearUnMensajeAAplicaciNResponse crearUnMensajeAAplicaciNResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAAplicaciNResponseBuilder() {
        crearUnMensajeAAplicaciNResponse = new CrearUnMensajeAAplicaciNResponse();
    }

    public CrearUnMensajeAAplicaciNResponseBuilder data(Data5 data) {
        crearUnMensajeAAplicaciNResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAAplicaciNResponse build() {
        return crearUnMensajeAAplicaciNResponse;
    }
}