/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CrearUnMensajeAlGrupoRequestBuilder {
    //the instance to build
    private CrearUnMensajeAlGrupoRequest crearUnMensajeAlGrupoRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CrearUnMensajeAlGrupoRequestBuilder() {
        crearUnMensajeAlGrupoRequest = new CrearUnMensajeAlGrupoRequest();
    }

    public CrearUnMensajeAlGrupoRequestBuilder leido(boolean leido) {
        crearUnMensajeAlGrupoRequest.setLeido(leido);
        return this;
    }

    public CrearUnMensajeAlGrupoRequestBuilder borrado(boolean borrado) {
        crearUnMensajeAlGrupoRequest.setBorrado(borrado);
        return this;
    }

    public CrearUnMensajeAlGrupoRequestBuilder data(Data data) {
        crearUnMensajeAlGrupoRequest.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CrearUnMensajeAlGrupoRequest build() {
        return crearUnMensajeAlGrupoRequest;
    }
}