/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Data14Builder {
    //the instance to build
    private Data14 data14;

    /**
     * Default constructor to initialize the instance
     */
    public Data14Builder() {
        data14 = new Data14();
    }

    public Data14Builder type(String type) {
        data14.setType(type);
        return this;
    }

    public Data14Builder url(String url) {
        data14.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data14 build() {
        return data14;
    }
}