/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Data5Builder {
    //the instance to build
    private Data5 data5;

    /**
     * Default constructor to initialize the instance
     */
    public Data5Builder() {
        data5 = new Data5();
    }

    public Data5Builder id(String id) {
        data5.setId(id);
        return this;
    }

    public Data5Builder leido(boolean leido) {
        data5.setLeido(leido);
        return this;
    }

    public Data5Builder borrado(boolean borrado) {
        data5.setBorrado(borrado);
        return this;
    }

    public Data5Builder fecha(String fecha) {
        data5.setFecha(fecha);
        return this;
    }

    public Data5Builder data(Data6 data) {
        data5.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data5 build() {
        return data5;
    }
}