/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Data5 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5759013243152099975L;
    private String id;
    private boolean leido;
    private boolean borrado;
    private String fecha;
    private Data6 data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leido")
    public boolean getLeido ( ) { 
        return this.leido;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leido")
    public void setLeido (boolean value) { 
        this.leido = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("borrado")
    public boolean getBorrado ( ) { 
        return this.borrado;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("borrado")
    public void setBorrado (boolean value) { 
        this.borrado = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fecha")
    public String getFecha ( ) { 
        return this.fecha;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fecha")
    public void setFecha (String value) { 
        this.fecha = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public Data6 getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (Data6 value) { 
        this.data = value;
    }
 
}
 