/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DataBuilder {
    //the instance to build
    private Data data;

    /**
     * Default constructor to initialize the instance
     */
    public DataBuilder() {
        data = new Data();
    }

    public DataBuilder type(String type) {
        data.setType(type);
        return this;
    }

    public DataBuilder numero(int numero) {
        data.setNumero(numero);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data build() {
        return data;
    }
}