/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class Data6Builder {
    //the instance to build
    private Data6 data6;

    /**
     * Default constructor to initialize the instance
     */
    public Data6Builder() {
        data6 = new Data6();
    }

    public Data6Builder type(String type) {
        data6.setType(type);
        return this;
    }

    public Data6Builder referencia(String referencia) {
        data6.setReferencia(referencia);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data6 build() {
        return data6;
    }
}