/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Data 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5500508960044727006L;
    private String type;
    private int numero;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("numero")
    public int getNumero ( ) { 
        return this.numero;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("numero")
    public void setNumero (int value) { 
        this.numero = value;
    }
 
}
 