/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Data6 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4956329721692754817L;
    private String type;
    private String referencia;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referencia")
    public String getReferencia ( ) { 
        return this.referencia;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referencia")
    public void setReferencia (String value) { 
        this.referencia = value;
    }
 
}
 