/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DatumBuilder {
    //the instance to build
    private Datum datum;

    /**
     * Default constructor to initialize the instance
     */
    public DatumBuilder() {
        datum = new Datum();
    }

    public DatumBuilder id(String id) {
        datum.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Datum build() {
        return datum;
    }
}