/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerGruposResponseBuilder {
    //the instance to build
    private LeerGruposResponse leerGruposResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerGruposResponseBuilder() {
        leerGruposResponse = new LeerGruposResponse();
    }

    public LeerGruposResponseBuilder data(List<Data5> data) {
        leerGruposResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerGruposResponse build() {
        return leerGruposResponse;
    }
}