/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerUnGrupoPorNombreResponseBuilder {
    //the instance to build
    private LeerUnGrupoPorNombreResponse leerUnGrupoPorNombreResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerUnGrupoPorNombreResponseBuilder() {
        leerUnGrupoPorNombreResponse = new LeerUnGrupoPorNombreResponse();
    }

    public LeerUnGrupoPorNombreResponseBuilder data(Data5 data) {
        leerUnGrupoPorNombreResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerUnGrupoPorNombreResponse build() {
        return leerUnGrupoPorNombreResponse;
    }
}