/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerUnMensajeResponseBuilder {
    //the instance to build
    private LeerUnMensajeResponse leerUnMensajeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerUnMensajeResponseBuilder() {
        leerUnMensajeResponse = new LeerUnMensajeResponse();
    }

    public LeerUnMensajeResponseBuilder data(Data5 data) {
        leerUnMensajeResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerUnMensajeResponse build() {
        return leerUnMensajeResponse;
    }
}