/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerAplicacionesResponseBuilder {
    //the instance to build
    private LeerAplicacionesResponse leerAplicacionesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerAplicacionesResponseBuilder() {
        leerAplicacionesResponse = new LeerAplicacionesResponse();
    }

    public LeerAplicacionesResponseBuilder data(List<Datum> data) {
        leerAplicacionesResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerAplicacionesResponse build() {
        return leerAplicacionesResponse;
    }
}