/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerMensajesResponseBuilder {
    //the instance to build
    private LeerMensajesResponse leerMensajesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerMensajesResponseBuilder() {
        leerMensajesResponse = new LeerMensajesResponse();
    }

    public LeerMensajesResponseBuilder data(List<Data5> data) {
        leerMensajesResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerMensajesResponse build() {
        return leerMensajesResponse;
    }
}