/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class LeerUnGrupoResponseBuilder {
    //the instance to build
    private LeerUnGrupoResponse leerUnGrupoResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeerUnGrupoResponseBuilder() {
        leerUnGrupoResponse = new LeerUnGrupoResponse();
    }

    public LeerUnGrupoResponseBuilder data(Data5 data) {
        leerUnGrupoResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeerUnGrupoResponse build() {
        return leerUnGrupoResponse;
    }
}