/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ModificarUnGrupoRequestBuilder {
    //the instance to build
    private ModificarUnGrupoRequest modificarUnGrupoRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ModificarUnGrupoRequestBuilder() {
        modificarUnGrupoRequest = new ModificarUnGrupoRequest();
    }

    public ModificarUnGrupoRequestBuilder nombre(String nombre) {
        modificarUnGrupoRequest.setNombre(nombre);
        return this;
    }

    public ModificarUnGrupoRequestBuilder aplicacion(String aplicacion) {
        modificarUnGrupoRequest.setAplicacion(aplicacion);
        return this;
    }

    public ModificarUnGrupoRequestBuilder usuarios(List<String> usuarios) {
        modificarUnGrupoRequest.setUsuarios(usuarios);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ModificarUnGrupoRequest build() {
        return modificarUnGrupoRequest;
    }
}