/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ModificarUnGrupoResponseBuilder {
    //the instance to build
    private ModificarUnGrupoResponse modificarUnGrupoResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ModificarUnGrupoResponseBuilder() {
        modificarUnGrupoResponse = new ModificarUnGrupoResponse();
    }

    public ModificarUnGrupoResponseBuilder data(Data5 data) {
        modificarUnGrupoResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ModificarUnGrupoResponse build() {
        return modificarUnGrupoResponse;
    }
}