/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ModificarUnMensajeLeidoBorradoResponseBuilder {
    //the instance to build
    private ModificarUnMensajeLeidoBorradoResponse modificarUnMensajeLeidoBorradoResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ModificarUnMensajeLeidoBorradoResponseBuilder() {
        modificarUnMensajeLeidoBorradoResponse = new ModificarUnMensajeLeidoBorradoResponse();
    }

    public ModificarUnMensajeLeidoBorradoResponseBuilder data(Data5 data) {
        modificarUnMensajeLeidoBorradoResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ModificarUnMensajeLeidoBorradoResponse build() {
        return modificarUnMensajeLeidoBorradoResponse;
    }
}