/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ModificarUnGrupoPorNombreResponseBuilder {
    //the instance to build
    private ModificarUnGrupoPorNombreResponse modificarUnGrupoPorNombreResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ModificarUnGrupoPorNombreResponseBuilder() {
        modificarUnGrupoPorNombreResponse = new ModificarUnGrupoPorNombreResponse();
    }

    public ModificarUnGrupoPorNombreResponseBuilder data(Data5 data) {
        modificarUnGrupoPorNombreResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ModificarUnGrupoPorNombreResponse build() {
        return modificarUnGrupoPorNombreResponse;
    }
}