/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ModificarUnGrupoRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4746726754426568312L;
    private String nombre;
    private String aplicacion;
    private List<String> usuarios;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("nombre")
    public String getNombre ( ) { 
        return this.nombre;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("nombre")
    public void setNombre (String value) { 
        this.nombre = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aplicacion")
    public String getAplicacion ( ) { 
        return this.aplicacion;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aplicacion")
    public void setAplicacion (String value) { 
        this.aplicacion = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usuarios")
    public List<String> getUsuarios ( ) { 
        return this.usuarios;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usuarios")
    public void setUsuarios (List<String> value) { 
        this.usuarios = value;
    }
 
}
 