/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ModificarUnGrupoPorNombreRequestBuilder {
    //the instance to build
    private ModificarUnGrupoPorNombreRequest modificarUnGrupoPorNombreRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ModificarUnGrupoPorNombreRequestBuilder() {
        modificarUnGrupoPorNombreRequest = new ModificarUnGrupoPorNombreRequest();
    }

    public ModificarUnGrupoPorNombreRequestBuilder nombre(String nombre) {
        modificarUnGrupoPorNombreRequest.setNombre(nombre);
        return this;
    }

    public ModificarUnGrupoPorNombreRequestBuilder aplicacion(String aplicacion) {
        modificarUnGrupoPorNombreRequest.setAplicacion(aplicacion);
        return this;
    }

    public ModificarUnGrupoPorNombreRequestBuilder usuarios(List<String> usuarios) {
        modificarUnGrupoPorNombreRequest.setUsuarios(usuarios);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ModificarUnGrupoPorNombreRequest build() {
        return modificarUnGrupoPorNombreRequest;
    }
}