/*
 * APIBuzonesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import com.example.controllers.*;
import com.example.http.client.HttpClient;

public class APIBuzonesClient {
    /**
     * Singleton access to Messages controller
     * @return	Returns the MessagesController instance 
     */
    public MessagesController getMessages() {
        return MessagesController.getInstance();
    }

    /**
     * Singleton access to Grupos controller
     * @return	Returns the GruposController instance 
     */
    public GruposController getGrupos() {
        return GruposController.getInstance();
    }

    /**
     * Singleton access to Boxes controller
     * @return	Returns the BoxesController instance 
     */
    public BoxesController getBoxes() {
        return BoxesController.getInstance();
    }

    /**
     * Singleton access to Applications controller
     * @return	Returns the ApplicationsController instance 
     */
    public ApplicationsController getApplications() {
        return ApplicationsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public APIBuzonesClient() {
    }

}